version: '3'
services:
  web:
    build: .
    ports:
    - "8080:8080"
    - "443:443"
    - "80:80"
    volumes:
    - .:/code
    - logvolume01:/var/log
    links:
    - postgres
  postgres:
    image: postgres
volumes:
  logvolume01: {}
